### ISSUE TITLE
Project definition file

### ISSUE THREAD

**Issue by v79** [v79/Cantilever#25]
A lot of values are currently hard-coded, such as folder paths. And there's nowhere to store project-level values such as website names.

Definite a project.yaml file. Create route for editing the project defintion, and a web UI for this. Create a UI for starting a new project.

**Comment by v79** [comment]
Possible content for the project yaml file (probably call it cantilever.yaml to avoid confusion with previous meanings of the word 'project' across the project).

- project name
- domain name
- primary author
- image resolutions
- folder paths?

**Comment by v79** [comment]
Example content from Bascule yaml file:

```yaml
siteName: Liam John Davison
dateFormat: "dd/MM/yyyy"
dateTimeFormat: HH:mm:ss dd/MM/yyyy
author: Liam Davison
theme: liamjd-theme
postsPerPage: 10
host: http://www.liamjd.org/
postLayouts: [devlog,post]

directories:
  source: sources
  output: site
  assets: assets
  templates: liamjd-theme/templates
  custom:
    posts: posts
    pdf: pdf
    pdfTemplates: liamjd-theme/templates/fop
s3:
  bucket: ljdtesting
generators: [IndexPageGenerator, PostNavigationGenerator, MultiTaxonomyNavigationGenerator, org.liamjd.bascule.extra.generators.sitemap.SitemapXMLGenerator, org.liamjd.bascule.extra.generators.lunr.LunrJSIndexGenerator]
extensions: [ ]
# org.liamjd.bascule.flexmark.spotify.SpotifyExtension
# org.liamjd.bascule.extra.generators.aws.s3.S3BucketUpload
# org.liamjd.bascule.extra.generators.pdf.SitePDFGenerator
$debug: false
```
